/**:
  pf_r2000:
    ros__parameters:
      transport: "udp"
      scanner_ip: "192.168.3.30"
      # port: "3000" # optional
      device: "R2000"
      start_angle: -1800000
      max_num_points_scan: 0
      packet_type: "C"
      scan_topic: "main/scan"
      frame_id: "main_lidar_link"
      watchdogtimeout: 60000
      watchdog: true
